### ISSUE TITLE
Add support for the sandbox environment

### ISSUE THREAD

**Issue by alex4671** [devoxa/paddle-sdk#422]
Is it possible to add the ability to switch to Sandbox Environment?
(to work, you need to replace ```https://vendors.paddle.com/api/2.0``` with ```https://sandbox-vendors.paddle.com/api/2.0```).
I tried to do it myself but ```generate-api-routes.ts``` doesn't work for me and I can't fix it

**Comment by queicherius** [comment]
Yeah this would definitely be a good feature to have -- this package is older than the sandbox environment, so it's currently not supported.

Likely the best way would be to change the generator to export out relative URLs and then have an optional base URL passed into the constructor.

**Comment by queicherius** [comment]
Added support for this in [v0.3.0](https://github.com/devoxa/paddle-sdk/releases/tag/v0.3.0) via a `baseUrl` option:

```ts
const paddleSdk = new PaddleSdk({
  baseUrl: 'https://sandbox-vendors.paddle.com/api',
  // ...
})
```

Let me know if this works for you :)
