### ISSUE TITLE
paddle-sdk does not allow empty metadata string in webhook raw payloads

### ISSUE THREAD

**Issue by aradzie** [devoxa/paddle-sdk#87]
Every time I am trying to call my webhook endpoint from the simulator in the dashboard I am receiving an error because the `passthrough` value cannot be parsed by paddle-sdk. The SDK expects this property to contain a JSON value which is encrypted to a non-empty, base64-encoded string. [Here](https://github.com/devoxa/paddle-sdk/blob/master/src/index.ts#L149) is the code fragment which does this. I can work-around by encrypting some empty value and giving it to webhook. But it would be nicer have the ability to customize the metadata parsing strategy.

```typescript
export interface PaddleSdkOptions<TMetadata = unknown> {
  /** Our public key to validate webhook requests */
  publicKey: string
  /** Our vendor id */
  vendorId: number
  /** Our vendor auth code */
  vendorAuthCode: string
  /**
   * A function which takes encoded metadata string from the `passthrough` property
   * and returns a parsed metadata value.
   * This function is free to throw any error if metadata parsing fails.
   */
  decodeMetadata: (passthrough: string) => TMetadata
}

export class PaddleSdk<TMetadata = unknown> {
  /** Returns a function which decodes metadata using the given encryption key */
  static decodeMetadata<TMetadata = unknown>(key: string) {
    return (passthrough: string): TMetadata => {
      return ... // TODO Implement this function.
    }
  }

  /** Returns a function which ignores the `passthrough` property and always returns `null` */
  static ignoreMetadata() {
    return (passthrough: string): null => {
      return null;
    }
  }
  ...
}

const sdk = new PaddleSdk({
  publicKey: '...',
  vendorId: 123,
  vendorAuthCode: '...',
  decodeMetadata: PaddleSdk.decodeMetadata('our secret key'),
})
```

Here I am proposing to replace the `metadataEncryptionKey` of the `PaddleSdkOptions` interface with a callback function which takes a string and decodes a value. Such a callback function can be obtained by calling `PaddleSdk.decodeMetadata` with an encryption key. Another example of the callback is `PaddleSdk.ignoreMetadata` which does nothing and always returns `null`.

**Comment by aradzie** [comment]
I can implement this feature myself. I realise that this will be a breaking change so I am asking your permission to proceed with a pull request to implement it.

**Comment by queicherius** [comment]
Hey, thanks for the issue and the PR! I marked it as a draft since you commented in it, but feel free to mark as ready for review whenever you feel like it's ready.

As for the topic itself - I'm happy to add this extra bit of customizability. From a quick glance at the PR it looks like you already accounted for encoding as well, and the code looks good. 

I'm thinking about if I want to release this as a breaking change, or if I want to default to the existing behaviour if no codec is provided, but an encryption key is set. Right now I'm trending towards just doing a clean major release.

**Comment by aradzie** [comment]
Thanks for the quick response! You project is in a really good shape, slick, clean, modern. The code generators are awesome. I am happy to contribute to the project.
I am trying to match your style as much as I can. Feel free to clean my changes afterwards. Please tell me how you sort imports. WebStorm has a really nice import sorter, but it produces too much difference from your style. ESLint has a rule for [sorting imports](https://eslint.org/docs/rules/sort-imports), is this what you use?

**Comment by queicherius** [comment]
> You project is in a really good shape, slick, clean, modern. The code generators are awesome. I am happy to contribute to the project.

Very glad to hear! 😃 

> Please tell me how you sort imports. WebStorm has a really nice import sorter, but it produces too much difference from your style. ESLint has a rule for sorting imports, is this what you use?

I am not entirely sure how I did it in this project, but I think it was the VSCode "Organize Imports" functionality.
